import * as z from "zod";
import { TemplateConfig } from "@/lib/services/nfc-cards.service";

export const templateSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  category: z.string().min(2, "Category must be at least 2 characters"),
  layoutKey: z.string().min(1, "Layout base is required"),
  config: z.object({
    primaryColor: z.string().optional(),
    secondaryColor: z.string().optional(),
    backgroundColor: z.string().optional(),
    backgroundType: z.enum(["solid", "gradient", "image"]).optional(),
    backgroundGradient: z.string().optional(),
    accentColor: z.string().optional(),
    textColor: z.string().optional(),
    cardStyle: z.string().optional(),
    buttonStyle: z.enum(["rounded", "sharp", "pill"]).optional(),
    avatarStyle: z.enum(["circle", "square", "rounded"]).optional(),
    glassmorphism: z.boolean().optional(),
    shadowIntensity: z.enum(["none", "low", "medium", "high"]).optional(),
    sectionsOrder: z.array(z.string()).optional(),
    avatarAlignment: z.enum(["left", "center", "right"]).optional(),
    infoAlignment: z.enum(["left", "center", "right"]).optional(),
    socialsLayout: z.enum(["grid", "list"]).optional(),
    socialsAlignment: z.enum(["left", "center", "right"]).optional(),
    actionsAlignment: z.enum(["left", "center", "right"]).optional(),
    primaryButtonColor: z.string().optional(),
    primaryButtonTextColor: z.string().optional(),
    secondaryButtonColor: z.string().optional(),
    secondaryButtonTextColor: z.string().optional(),
    primaryButtonLabel: z.string().optional(),
    secondaryButtonLabel: z.string().optional(),
    bioAlignment: z.enum(["left", "center", "right"]).optional(),
    // Card Specifics
    cardPrimaryColor: z.string().optional(),
    cardSecondaryColor: z.string().optional(),
    cardTextColor: z.string().optional(),
    cardLayoutKey: z.string().optional(),
    cardPattern: z.enum(["none", "dots", "grid", "diagonal", "waves"]).optional(),
    cardBackgroundImage: z.string().optional(),
    pagePattern: z.enum(["none", "dots", "grid", "diagonal", "waves"]).optional(),
    cardLogoAlignment: z.enum(["left", "right", "center"]).optional(),
    cardNameAlignment: z.enum(["left", "right", "center"]).optional(),
    cardShowPattern: z.boolean().optional(),
    showAvatar: z.boolean().optional(),
    showHeader: z.boolean().optional(),
    showBio: z.boolean().optional(),
    showSocials: z.boolean().optional(),
    showActions: z.boolean().optional(),
    showFooter: z.boolean().optional(),
    bioText: z.string().optional(),
    headerImage: z.string().optional(),
    contentSpacing: z.enum(["compact", "relaxed", "loose"]).optional(),
    showQrCode: z.boolean().optional(),
    showSocialLinks: z.boolean().optional(),
    showVCard: z.boolean().optional(),
    showVerifyBadge: z.boolean().optional(),
    headerStyle: z.enum(["minimal", "standard", "grand"]).optional(),
    fontFamily: z.string().optional(),
    backgroundImage: z.string().optional(),
    topBadgeText: z.string().optional(),
    verifyBadgeText: z.string().optional(),
    showTopBadge: z.boolean().optional(),
    cardShowEmail: z.boolean().optional(),
    cardShowPhone: z.boolean().optional(),
    cardDetailsAlignment: z.enum(["left", "right", "center"]).optional(),
    showSocialLabels: z.boolean().optional(),
    socialsIconColor: z.string().optional(),
    socialsButtonColor: z.string().optional(),
    socialsFillColor: z.string().optional(),
  }).optional(),
});

export type TemplateFormValues = z.infer<typeof templateSchema>;

export const DEFAULT_CONFIG: TemplateConfig = {
  primaryColor: "#000000",
  backgroundColor: "#ffffff",
  backgroundType: "solid",
  backgroundGradient: "",
  accentColor: "#3b82f6",
  textColor: "#0f172a",
  cardStyle: "brutalist",
  buttonStyle: "sharp",
  avatarStyle: "square",
  glassmorphism: false,
  shadowIntensity: "none",
  sectionsOrder: ["avatar", "header", "bio", "socials", "actions", "footer"],
  avatarAlignment: "center",
  infoAlignment: "center",
  socialsLayout: "grid",
  socialsAlignment: "center",
  actionsAlignment: "center",
  primaryButtonColor: "",
  primaryButtonTextColor: "#ffffff",
  secondaryButtonColor: "",
  secondaryButtonTextColor: "#000000",
  primaryButtonLabel: "",
  secondaryButtonLabel: "",
  bioAlignment: "center",
  cardLogoAlignment: "right",
  cardNameAlignment: "left",
  cardShowPattern: true,
  cardShowEmail: true,
  cardShowPhone: true,
  cardDetailsAlignment: "left",
  showSocialLabels: true,
  cardPrimaryColor: "#ffffff",
  cardSecondaryColor: "#101312",
  cardTextColor: "#0f172a",

  cardPattern: "none",
  cardBackgroundImage: "",
  pagePattern: "none",
  showAvatar: true,
  showHeader: true,
  showBio: true,
  showSocials: true,
  showActions: true,
  showFooter: true,
  bioText: "Designing the future of digital identity.",
  contentSpacing: "relaxed",
  showQrCode: true,
  showSocialLinks: true,
  showVCard: true,
  showVerifyBadge: true,
  headerStyle: "standard",
  fontFamily: "Inter",
  backgroundImage: "",
  topBadgeText: "Digital Business Card",
  verifyBadgeText: "Identity Verified",
  showTopBadge: true,
};
